### ISSUE TITLE
Race condition on kubernetes resources when cdk deploy 

### ISSUE THREAD

**Issue by allamand** [yjw113080/aws-cdk-eks-multi-region#6]
Hi Jiwon,

I tried to deploy from here and I got the same issue we already discuss:

```
2:57:52 PM | CREATE_FAILED        | Custom::AWSCDK-EKS-KubernetesResource | demogo-cluster/man...1/Resource/Default
Failed to create resource. Error: b'Error from server (NotFound): error when creating "/tmp/manifest.yaml": namespaces "management" not found\n'

Logs: /aws/lambda/ClusterStack-us-west-2-awscdkawsek-Handler886CB40B-1FEST0C980QRJ

at invokeUserFunction (/var/task/framework.js:95:19)
at process._tickCallback (internal/process/next_tick.js:68:7)
```

I'll  try a PR to fix this issue, If you accept it, we'll have to update also the skelton and the workshop, so let's discuss it then

seb

**Comment by 4patelr** [comment]
I encountered this same error and found that it was due to missing Namespace entry in the 00_namespaces.yaml.

```
apiVersion: v1
kind: Namespace
metadata:
   name: management
```
